content:
  name: homepage
  label: Home Page
  type: file
  path: _homepage
  fields:
    - { name: maintitle, label: Main Title, type: string, required: true }
    - { name: mainsubtitle, label: Main Subtitle, type: string, required: true }
    - { name: tagline, label: Tagline, type: string, required: true }
    - { name: aboutTitle, label: About Title, type: string, required: true }
    - { name: aboutSubtitle, label: About Subtitle, type: string, required: true }
    - { name: aboutDesc, label: About Description, type: string}
    - { name: valueTitle, label: Corporate Values Title, type: string, required: true }
    - { name: valuesubtitle, label: Corporate Values Subtitle, type: string }
    - { name: valuesDesc, label: Corporate Values Description, type: string, required: true }
content:
  - name: test
    label: Our Brands
    type: collection
    path: _posts
    view:
      fields: [ coverImage, title, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: excerpt, label: Excerpt, type: string }
      - { name: coverImage, label: Cover image, type: image }
      - { name: date, label: Date, type: date, options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" } }
      - name: author
        label: Author
        type: object
        fields:
          - { name: name, label: Name, type: string }
          - { name: picture, label: Picture, type: image }
      - name: ogImage
        label: Image (social sharing)
        type: object
        fields:
          - { name: url, label: URL, type: image }
      - { name: body, label: Body, type: rich-text }
      
media:
  input: public/assets
  output: /assets
  categories: [ "image" ]
content:
  - name: ourBrands
    label: Our Brands
    type: collection
    path: _posts
    view:
      fields: [ coverImage, title, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: excerpt, label: Excerpt, type: string }
      - { name: coverImage, label: Cover image, type: image }
      - { name: date, label: Date, type: date, options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" } }
      - name: author
        label: Author
        type: object
        fields:
          - { name: name, label: Name, type: string }
          - { name: picture, label: Picture, type: image }
      - name: ogImage
        label: Image (social sharing)
        type: object
        fields:
          - { name: url, label: URL, type: image }
      - { name: body, label: Body, type: rich-text }